L1FrontierCEM <- function(treatment, dataset, drop, breaks=NULL){
  gs <- getStrata(treatment, dataset, drop, breaks=breaks)
  strata <- gs$strata
  mycut <- gs$mycut
  names(strata) <- dataset[,which(colnames(dataset) == treatment)]
  unique.strata <- unique(strata)
  strataholder <- list()
  for(i in 1:length(unique.strata)){
    strataholder[[i]] <- which(strata==unique.strata[i])
  }
  drops <- c()
  L1s <- c()
  samplesize <- c()
  wList <- list()

  ## calculate the L1 of the whole dataset
  imb <- L1(strataholder)


      imbalance(group=dataset[[treatment]], data=dataset, drop=drop, breaks = breaks)
  ## save the breaks that were randomly generated by the imbalance functinonyu 
  if(is.null(breaks)){breaks< - imb$L1$breaks}
  L1s <- c(L1s, imb$L1$L1)
  samplesize <- c(samplesize, nrow(dataset))
  W <- rep(1,nrow(dataset))
  names(W) <- rownames(dataset)
  wList[[1]] <- W
  ## use cem to identify the singletons
  cem1 <- cem(treatment=treatment,data=dataset,cutpoints=breaks,L1.breaks=breaks,eval.imbalance=T, drop=drop)
  L1s <- c(L1s, cem1$imbalance$L1$L1)
  samplesize <- c(samplesize, sum(cem1$tab["Matched",]))
  W <- cem1$w
  names(W) <- rownames(dataset)
  wList[[2]] <- W
  
  #return(list(balance = L1s, drops = unname(drops), samplesize=samplesize, metric="L1-2", breaks=breaks))
  return(list(balance = L1s, samplesize=samplesize, metric="L1w", breaks=mycut, weights=wList))
}

